---
- name: Include OS-specific variables (Debian)
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Include OS-specific variables (RHEL)
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "RedHat"

- name: Define ntp package
  set_fact:
    ntp_package: "{{ __ntp_package }}"
  when: ntp_package is not defined

- name: Define ntp service
  set_fact:
    ntp_service: "{{ __ntp_service }}"
  when: ntp_service is not defined

- name: Install ntp package
  package:
    name: "{{ ntp_package }}"
    state: present
  notify: Restart ntp

- meta: flush_handlers
...
